config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'

  resources :users
  resources :listings
  resources :reservations
  resources :reviews

end

app/models/admin.rb
class Admin < User

end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :imageable, polymorphic: true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                                          :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :location
  validates_presence_of :rate

  belongs_to :user
  has_many :reviews

  has_many :images, as: :imageable
  has_many :reservations
  has_many :users, through: :reservations
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing

  validates_presence_of :start_date
  validates_presence_of :end_date
end

app/models/review.rb
class Review <ActiveRecord::Base
  validates_presence_of :content
  validates_presence_of :rating
  validates_presence_of :user_id
  validates_presence_of :listing_id
  belongs_to :user
 belongs_to :listing 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_uniqueness_of :username
  validates_presence_of :name

  has_many :listings

  has_many :images, as: :imageable

  has_many :reviews

  has_many :reservations
  #See http://stackoverflow.com/questions/18690700/multiple-has-many-relationships-to-same-model
  has_many :reserved_listings, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |params| params.permit(:username, :name, :email) }
    devise_parameter_sanitizer.for(:sign_up) { |params| params.permit(:username, :name, :email, :password, :avatar )}
    devise_parameter_sanitizer.for(:account_update) { |params| params.permit(:username, :name, :email, :current_password) }
  end

end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  def index

  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # before_action will call the specified method before each of the controller actions listed after 'only'
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    @listings = Listing.all
  end

  def show
    @reservation = Reservation.new
  end

  def create
    @image = Image.create avatar: params[:listing][:avatar]
    @listing = Listing.new listing_params
    if @listing.save
      @listing.images.push @image
      flash[:notice] = 'Listing successfully saved'
      redirect_to listing_path @listing
    else
      flash[:notice] = 'Try again'
      redirect_to user_path listing_params[:user_id]
    end
  end

  def edit

  end

  def update
    if @listing.update listing_params
      flash[:notice] = "Listing saved"
      redirect_to listing_path @listing
    else
      flash[:notice] = "There was a problem saving your listing"
      render :edit
    end
  end

  def destroy
    # we already have @listing here
    @user = @listing.user
    @listing.destroy
    flash[:notice] = 'Listing deleted'
    redirect_to user_path @user
  end

private

  def set_listing
    @listing = Listing.find params[:id]
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :rate, :user_id, :location, :image)
  end
  #
  # def image_params
  #   params.require(:image).permit(:avatar)
  # end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
    @listing = Listing.find(reservation_params[:listing_id])
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:notice] = "You have successfully reserved this listing"
      redirect_to reservation_path @reservation
    else
      flash[:notice] = "Something went wrong, please try again"
      redirect_to listing_path @listing
    end
  end

private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :user_id, :listing_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @listing = Listing.find params[:listing_id]
  end

  def create
    @review = Review.new review_params
    @listing = Listing.find review_params[:listing_id]
    if @review.save
      flash[:notice] = 'Review created'
      redirect_to listing_path @listing
    else
      flash[:notice] = 'Something went wrong, please try again'
      render :new
    end
  end

private

  def review_params
    params.require(:review).permit(:content, :rating, :user_id, :listing_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show
    @listing = Listing.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <p class="lead">Uhoh, something went wrong! Please fix these errors:</p>
    <% object.errors.full_messages.each do |message| %>
      <div class="alert alert-danger alert-dismissible alert-sm" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirBnbClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "WaterBnB", root_path, class: "navbar-brand" %>
      </div>
      <ul class='nav navbar-nav'>
        <li><%= link_to "View all listings", listings_path %></li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>

        <% if user_signed_in? %>
          <p class="navbar-text">Signed in as <%= link_to current_user.username, user_path(current_user) %></p>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>


      </ul>
    </div>
  </nav>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>

</body>
</html>

app/views/listings/_form.html.erb
<%= render 'layouts/errors', object: @listing %>

<%= bootstrap_form_for @listing do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :description %>
  <%= f.text_field :location %>
  <%= f.number_field :rate %>
  <%= f.file_field :avatar %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit %>
<% end %>

app/views/listings/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h3>Edit your listing:</h3>
  <%= render 'form' %>
</div>

app/views/listings/index.html.erb
<h3 class="text-center">Current Listings</h3>

<% if @listings %>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Location</th>
        <th>Rate</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @listings.each do |listing| %>
        <tr>
          <td>
            <%= link_to listing_path(listing) do %>
              <%= listing.title %>
            <% end %>
          </td>
          <td><%= listing.description %></td>
          <td><%= listing.location %></td>
          <td>$<%= listing.rate %></td>
          <% if current_user == listing.user %>
            <td><%= link_to "Edit", edit_listing_path(listing) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>


<% end %>

app/views/listings/show.html.erb
<div class="row">
  <!-- images -->
  <% if @listing.images.any? %>
    <div class="col-md-6">
      <% @listing.images.each do |image| %>
        <%= image_tag image.avatar.url(:medium), class: "img-responsive img-rounded"%>
      <% end %>
    </div>
  <% end %>

  <!-- description -->
  <div class="col-md-6">
    <h3 class="text-center"> <%= @listing.title %>
      <small class="muted">$<%= @listing.rate %>/night</small>
    </h3>
    <h4 class="text-center"> <%= @listing.location %></h4>
    <p class="lead"><%= @listing.description %></p>
    <br>
    <% if current_user %>
      <%= bootstrap_form_for @reservation do |f| %>
        <%= f.date_field :start_date %>
        <%= f.date_field :end_date %>
        <%= f.hidden_field :listing_id, value: @listing.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.submit "Rent", class: "btn btn-info btn-block" %>
      <% end %>
      <br>

      <!-- Review/Reviews -->
      <!-- Pass in :listing_id to url so that it is available in the params -->
      <%= link_to 'Review', new_review_path(listing_id: @listing.id), class: "btn btn-default btn-block" %>
      <br>
    <% end %>

    <% if @listing.reviews %>
      <% @listing.reviews.each do |review| %>
        <blockquote>
          <p><%= review.content %>
            <% (5-review.rating).times do %>
              <span class="glyphicon glyphicon-star-empty pull-right" aria-hidden="true"></span>
            <% end %>
            <% review.rating.times do %>
              <span class="glyphicon glyphicon-star pull-right" aria-hidden="true"></span>
            <% end %>
          </p>
        </blockquote>
        </li>
      <% end %>
    <% end %>
  </div>
</div>

app/views/reservations/show.html.erb
Rental dates

app/views/reviews/new.html.erb
<h2>Write a review:</h2>

<%= bootstrap_form_for @review do |f| %>
  <%= f.text_area :content, rows: 5 %>
  <div class='col-md-1'>
    <%= f.select(:rating, options_for_select([['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), inline: true) %>
    <%= f.hidden_field :listing_id, value: @listing.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class='col-md-1'>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>hi</h1>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1 class="text-center">Hi, <%= current_user.name %></h1>
<hr>
<div class="col-md-6">
  <% if current_user.listings %>
    <p class="lead">Your current listings:</p>
    <ul class="list-group">
      <% current_user.listings.each do |listing| %>
        <li class="list-group-item"><%= listing.title %>
        <span class="pull-right"><%= link_to ' Delete', listing_path(listing), data: {confirm: 'Are you sure?', method: 'delete'} %> | 
        <%= link_to 'Edit', edit_listing_path(listing) %></span></li>
      <% end %>
    </ul>
  <% else %>
    <p class="lead">You don't have any listings yet</p>
  <% end %>


</div>

<div class="col-md-6">
  <p class="lead">Create a new listing, <%= current_user.name %></p>
  <%= render 'listings/form' %>
</div>